Flatencoding parsing: automatically handle date/time/date_time precision
ehrbase/openEHR_SDK pull request #352
Opened 2022-04-08 12:36 UTC by mhenke-vg

Make the implementation handle input that does not fit perfectly by taking the parts that can be used 

e.g. DateTime input into Date field only takes the date part

2022-04-11 06:11 UTC, stefanspiska requested changes
can you please add test.

In fact there are test for this bug in org.ehrbase.conformance_test.extern.tests.SettersTest wich you could simple enable by remover the overwrite
also you have  Errors in you tesst

2022-04-13 11:14 UTC, serefarikan commented
@mhenke-vg @stefanspiska This is surely an interesting one. May I be the devil's advocate and remind that according to openEHR RM, [there is not a IS_A relationship between Date and DateTime types](https://specifications.openehr.org/releases/RM/latest/data_types.html#_overview_5). If I was the developer using the flat encoding, I'd expect a DateTime input into a Date field to fail because of this.

If a DateTime is provided, at least as per the RM, it means the time is significant, and I'd say it'd have to be valid or invalid as a whole. What if someone is recording the time some medication was administered at 15:00 PM during the day, and the next dose must be taken at 23:00 PM. If the conversion to Date falls back to mid day for the time component, then the patient would be given the medication at 20:00, and would risk having a stomach bleeding etc..

Apologies if I misunderstood things, just thought I'd raise the point :)

2022-04-27 09:40 UTC, stefanspiska approved these changes

2022-04-27 09:40 UTC, merged

2022-04-27 15:07 UTC, freshehr commented
For what it is worth, I partly agree with @serefarikan here. The original archetype designer will have selected DV_DATE  for a reason, and it feels as if there might be some potential risk if a full DateTime is being automatically curtailed to to Date inside the CDR. I do think it is probably valid to do so in the majority of cases but I'd have preferred for this to be checked first for clinical safety and any  safe transform applied outside the CDR.