CDR-587 Make AqlPath immutable
ehrbase/openEHR_SDK pull request #402
Opened 2022-10-24 07:14 UTC by HolgerReiseVSys

- PredicateLogicalAndOperation immutable
- introduced CharSequenceHelper::trim

2022-10-24 12:04 UTC, vmueller-vg requested changes

2022-10-25 09:21 UTC, HolgerReiseVSys commented on aql/src/main/java/org/ehrbase/aql/dto/path/predicate/PredicateHelper.java
> +            if (cmpOp.getSymbol() == ConditionComparisonOperatorSymbol.EQ
Yes, the behavior has changed, but it seems `Interpreter::findPathToValue` is the only caller and `EQ` is implied there.
I have separated the filter from the removeInternal method.

2022-10-25 09:29 UTC, vmueller-vg commented on aql/src/main/java/org/ehrbase/aql/dto/path/predicate/PredicateHelper.java
> +            if (cmpOp.getSymbol() == ConditionComparisonOperatorSymbol.EQ
fine with me. maybe we could rename the "remove" method to "removeEq" or something like that and adjust the javadoc

2022-10-26 10:57 UTC, HolgerReiseVSys commented on aql/src/main/java/org/ehrbase/aql/dto/path/predicate/PredicateHelper.java
> +            if (cmpOp.getSymbol() == ConditionComparisonOperatorSymbol.EQ
We decided to add the symbol as a parameter

2022-10-26 16:59 UTC, merged