Feature/cdr 1057 term mappings can not be saved in name via flat
ehrbase/openEHR_SDK pull request #519
Opened 2023-09-27 08:02 UTC by dmitrytulba

# Changes

> Describe your changes in a short and concise list.

# Related issue

> Reference related issues, and use one of the [closing keywords, e.g. closes or fixes](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link the corresponding issue, if any.

# Additional information 

> Provide additional information for this change, if needed.

# Pre-Merge checklist

- [ ] New code is tested
- [ ] Present and new tests pass
- [ ] Documentation is updated
- [ ] The build is working without errors
- [ ] No new Sonar issues introduced
- [ ] Changelog is updated
- [ ] Code has been reviewed

2023-10-04 12:31 UTC, vidi42 commented
Missing entry in the changelog

2023-10-06 09:51 UTC, stefanspiska requested changes
also add changelog

2023-10-06 09:51 UTC, stefanspiska commented on serialisation/src/main/java/org/ehrbase/openehr/sdk/serialisation/flatencoding/std/marshal/StdFromCompositionWalker.java
> +                || (!(currentNode != null && currentNode.getId().equals("name")) && isLocatable(parentNode))) {
currentNode.getId().equals("name")) && isLocatable(parentNode)

pull that in a method isNameAttribute

2023-10-11 11:37 UTC, stefanspiska approved these changes

2023-10-11 12:08 UTC, merged