Implemented partial date/time in ITEM_STRUCT
ehrbase/openEHR_SDK pull request #72
Opened 2020-08-28 07:16 UTC by chevalleyc

Changes db encoding with support for partial date time. 

See https://github.com/ehrbase/openEHR_SDK/blob/feature/197_partial_ISO_strings/serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/DBEncodeTest.java testDateTimeEncodeDecode() with composition example: https://github.com/ehrbase/openEHR_SDK/blob/feature/197_partial_ISO_strings/test-data/src/main/resources/composition/canonical_json/datetime_tests.json

This implementation requires https://github.com/openEHR/archie/pull/208 to perform as expected

2020-09-02 14:29 UTC, Geisterfalle reviewed
I checked this one with an diagnosis example. Based on your example composition I would assume that it should work, however, I get the following error related to archie:

`{
    "error": "Text '2020-09-02' could not be parsed at index 4:2020-09-02 (through reference chain: com.nedap.archie.rm.composition.Composition[\"content\"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Evaluation[\"data\"]->com.nedap.archie.rm.datastructures.ItemTree[\"items\"]->java.util.ArrayList[1]->com.nedap.archie.rm.datastructures.Element[\"value\"]->com.nedap.archie.rm.datavalues.quantity.datetime.DvDateTime[\"value\"])",
    "status": "Bad Request"
}`

I understand that required changes in Archie are already merged. Am I missing something, maybe in how I need to set up EHRbase to properly test?

2020-09-03 03:15 UTC, chevalleyc commented
> I checked this one with an diagnosis example. Based on your example composition I would assume that it should work, however, I get the following error related to archie:
> 
> `{ "error": "Text '2020-09-02' could not be parsed at index 4:2020-09-02 (through reference chain: com.nedap.archie.rm.composition.Composition[\"content\"]->java.util.ArrayList[0]->com.nedap.archie.rm.composition.Evaluation[\"data\"]->com.nedap.archie.rm.datastructures.ItemTree[\"items\"]->java.util.ArrayList[1]->com.nedap.archie.rm.datastructures.Element[\"value\"]->com.nedap.archie.rm.datavalues.quantity.datetime.DvDateTime[\"value\"])", "status": "Bad Request" }`
> 
> I understand that required changes in Archie are already merged. Am I missing something, maybe in how I need to set up EHRbase to properly test?

The changes are merged I believe, however make sure you rebuild everything from scratch (mvn clean), and check your archie version in your .m2 directory. I found mine was not properly updated for some reason hence causing the same issue.

2020-09-08 14:53 UTC, stefanspiska commented on serialisation/src/test/java/org/ehrbase/serialisation/dbencoding/DBEncodeTest.java
> +        Composition composition = new CanonicalJson().unmarshal(IOUtils.resourceToString("/composition/canonical_json/datetime_tests.json", UTF_8), Composition.class);
Please add datetime_tests.json to CompositionTestDataCanonicalJson and use that

2020-09-08 14:54 UTC, stefanspiska commented on serialisation/src/test/java/org/ehrbase/serialisation/jsonencoding/CanonicalJsonMarshallingTest.java
> +        assertNotNull(dvDate);
maybe test the value

2020-09-08 14:54 UTC, stefanspiska commented on serialisation/src/test/java/org/ehrbase/serialisation/jsonencoding/CanonicalJsonMarshallingTest.java
> +        assertNotNull(dvDateTime);
maybe test the value

2020-09-08 14:55 UTC, stefanspiska requested changes
Could you pleas use the enums in test-data module for test compositions.

Otherwise it looks good.

2020-09-11 02:58 UTC, merged